spring:
  application:
    name: server
  #autoconfigure:
    #exclude: import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
  datasource:
    url: jdbc:mysql://localhost:3306/serverdb
    password: 123456
    username: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true